version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # backendディレクトリ内のDockerfileを使用
    container_name: grahql-backend
    env_file:
      - ./backend/cmd/.env
    command: sh -c "sh ./init.sh"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db #コンテナ名を指定
    environment: # 環境変数を指定
      MYSQL_DATABASE: schedule_todo
      MYSQL_ROOT_PASSWORD: yourpassword
      TZ: "Asia/Tokyo" # タイムゾーンを指定
    ports:
      - "3300:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # ヘルスチェックを指定
      interval: 10s # チェック間隔
      timeout: 5s # タイムアウト
      retries: 3 # リトライ回数
     
