version: "3.8"

services:
  frontend:
    image: node:14-alpine # Node.js の公式イメージを指定
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # backendディレクトリ内のDockerfileを使用
    container_name: grahql-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/cmd
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db #コンテナ名を指定
    environment: # 環境変数を指定
      MYSQL_DATABASE: schedule_todo
      MYSQL_ROOT_PASSWORD: yourpassword
      TZ: "Asia/Tokyo" # タイムゾーンを指定
    ports:
      - "3300:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # ヘルスチェックを指定
      interval: 10s # チェック間隔
      timeout: 5s # タイムアウト
      retries: 3 # リトライ回数
