// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Todo struct {
    ID     string
    Text   string
    Done   bool
    User   *User   
    UserID string  }

type NewTodo struct {
    Text   string
    UserID string  
}

type User struct {
    ID   string
    Name string
}