type Schedule {
  scheduleid: ID!
  userid: ID
  subjectname: String
  classroomname: String
  dayofweek: Dayofweek!
  period: Int!
}

enum Dayofweek {
  Monday
  Tuesday
  Wednesday
  Thursday
  Friday
  Saturday
}

input NewSchedule {
  dayofweek: Dayofweek!
  period: Int!
  subjectname: String!
  classroomname: String!
}

extend type Query {
  schedules: [Schedule!]!
  schedule(userid: ID!): Schedule!
}

extend type Mutation {
  createschedule(input: NewSchedule!): Schedule!
}
