type Schedule {
  userid: ID!
  subjectid: ID
  classroom: Classroom!
  dayofweek: Dayofweek!
  period: Int!
}

enum Dayofweek {
  Monday
  Tuesday
  Wednesday
  Thursday
  Friday
  Saturday
}

input NewSchedule {
  dayofweek: Dayofweek!
  period: Int!
}

extend type Query {
  schedules: [Schedule!]!
  schedule(userid: ID!): Schedule!
}

extend type Mutation {
  createschedule(input: NewSchedule!): Schedule!
}
