type Subject {
  subjectid: ID!
  subjectname: String!
  todos: [Todo]
}

input NewSubject {
  subjectname: String!
}

extend type Query {
  subjects: [Subject!]!
  subject(subjectid: ID): Subject!
}

extend type Mutation {
  createSubject(input: NewSubject!): Subject!
}
