type Todo {
  userid: ID!
  title: String!
  completed: Boolean!
  subjectid: ID
}

input NewTodo {
  title: String!
  userid: ID!
  subjectid: ID
}
extend type Query {
  todos: [Todo!]!
  todo(userid: ID!): Todo!
}

extend type Mutation {
  createTodo(input: NewTodo!): Todo!
}
