type Todo {
  Todoid: ID!
  userid: ID!
  title: String!
  period: Int!
  completed: Boolean!
  subjectname: String
  classroomname: String
}

input NewTodo {
  title: String!
  period: Int!
  subjectname: String!
  classroomname: String!
}
extend type Query {
  todos: [Todo!]!
  todo(userid: ID!): Todo!
}

extend type Mutation {
  createTodo(input: NewTodo!): Todo!
}
