type Todo {
  todoid: String
  userid: ID!
  title: String
  period: Int!
  completed: Boolean!
  subjectname: String
  classroomname: String
}

input NewTodo {
  title: String
  period: Int!
  subjectname: String!
  classroomname: String!
  todoid: String
}
extend type Query {
  todos: [Todo!]!
  todo(userid: ID!): Todo!
  todosid(todoid: String!): Todo!
}

extend type Mutation {
  createTodo(input: NewTodo!): Todo!
}
