type Todo {
  id: ID!
  todoid: String
  userid: ID!
  title: String
  period: Int!
  completed: Boolean!
  subjectname: String
  classroomname: String
}

input NewTodo {
  title: String
  period: Int!
  subjectname: String
  classroomname: String
  todoid: String
  completed: Boolean!
}
extend type Query {
  todos(userid: ID!): [Todo!]!
  todo(userid: ID!): Todo!
  todosid(todoid: String!): Todo!
}

extend type Mutation {
  createTodo(input: NewTodo): Todo!
  updateTodoCompleted(todoid: String!): Todo!
}
