package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"strconv"

	"github.com/mashumarrow/todoapplication/backend/graph"
	"github.com/mashumarrow/todoapplication/backend/models"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input models.NewTodo) (*models.Todo, error) {
	// 認証されているユーザーのuserIDを取得
	userIDValue := ctx.Value("userID")
	var userID uint64

	if id, ok := userIDValue.(string); ok {
		// stringからuint64に変換
		parsedID, err := strconv.ParseUint(id, 10, 64)
		if err != nil {
			fmt.Println("Failed to parse user ID:", id) // 変換失敗時のログ
			return nil, fmt.Errorf("invalid user ID format")
		}
		userID = parsedID
		fmt.Println("User ID in handler:", userID) // デバッグログ
	} else {
		fmt.Println("Failed to get user ID from context:", userIDValue) // ここで何が返ってきたか確認
		return nil, fmt.Errorf("user not authenticated")
	}

	//  認証済みのユーザーIDを使用して Todo を作成
	todo := &models.Todo{
		Title:     input.Title,
		UserID:    uint(userID),
		//Dayofweek: input.Dayofweek,
		Period:    input.Period,
		Subjectname:   input.Subjectname,
		Classroomname: input.Classroomname,
	}

	// 5. データベースに新しい Todo を保存
	if err := r.DB.Create(todo).Error; err != nil {
		return nil, err
	}

	return todo, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*models.Todo, error) {
	var todos []*models.Todo

	if err := r.DB.Preload("Subject").Find(&todos).Error; err != nil {
		return nil, err
	}

	return todos, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, userid string) (*models.Todo, error) {
	var todo models.Todo
	if err := r.DB.Where("user_id = ?", userid).First(&todo).Error; err != nil {
		return nil, err
	}
	return &todo, nil
}

// Todoid is the resolver for the Todoid field.
func (r *todoResolver) Todoid(ctx context.Context, obj *models.Todo) (string, error) {
	return fmt.Sprintf("%d", obj.TodoID), nil
}

// Userid is the resolver for the userid field.
func (r *todoResolver) Userid(ctx context.Context, obj *models.Todo) (string, error) {
	return fmt.Sprintf("%d", obj.UserID), nil}

// Subjectname is the resolver for the subjectname field.
func (r *todoResolver) Subjectname(ctx context.Context, obj *models.Todo) (*string, error) {
	result := fmt.Sprintf("%d", obj.Subjectname)
return &result, nil
}

// Classroomname is the resolver for the classroomname field.
func (r *todoResolver) Classroomname(ctx context.Context, obj *models.Todo) (*string, error) {
	panic(fmt.Errorf("not implemented: Classroomname - classroomname"))
}

// Todo returns graph.TodoResolver implementation.
func (r *Resolver) Todo() graph.TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
